name: Send Scheduled Message

on:
  schedule:
    - cron: '0 0 * * *'    # 7:00 PM EST (2 hours before 9:00 PM EST)
    - cron: '30 3 * * *'   # 10:30 PM EST (2 hours before 12:30 AM EST)
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Google Chat message
        env:
          GCHAT_WEBHOOK_URL: https://chat.googleapis.com/v1/spaces/AAQA45f-Aoc/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=ondQWN9rd86LJTVuCVr8YInKBCA_QKaa_9m6Vz8ROIA
        run: |
          curl -X POST -H "Content-Type: application/json; charset=UTF-8" \
            -d '{"text":"Hello,\nCan you please check and update the load status"}' \
            "$GCHAT_WEBHOOK_URL"
